INSERT INTO `service` (`id`, `name`, `description`) VALUES
(1, 'hotel', 'Découvrez notre sélection des meilleurs hôtels de luxe soigneusement choisis pour vous offrir une expérience d\'hébergement incomparable. Confort, élégance et service personnalisé sont au rendez-vous.'),
(2, 'restaurant', 'Laissez-vous guider vers les tables les plus raffinées. De la gastronomie française aux cuisines du monde, nous sélectionnons pour vous les restaurants d\'exception qui éveilleront vos papilles.'),
(3, 'spa', 'Offrez-vous une parenthèse de bien-être absolu. Nos partenaires spas et instituts de beauté vous proposent des soins exclusifs pour vous ressourcer corps et âme.'),
(4, 'driver', 'Voyagez en toute sérénité avec nos chauffeurs privés professionnels. Ponctualité, discrétion et confort sont les maîtres mots de notre service de transport haut de gamme.'),
(5, 'event', 'Faites de chaque moment une occasion inoubliable. Soirées privées, événements d\'entreprise, célébrations — nos partenaires organisent des événements sur mesure à la hauteur de vos exigences.'),
(6, 'travel', 'Partez à la découverte du monde avec nos agences de voyage partenaires. Circuits exclusifs, voyages sur mesure et destinations d\'exception pour des aventures hors du commun.'),
(7, 'activity', 'Explorez une sélection d\'activités uniques et exclusives pour enrichir votre séjour. Des expériences culturelles aux aventures en plein air, nous avons ce qu\'il vous faut pour vivre des moments mémorables.'),
(8, 'vehicle', 'Découvrez notre flotte de véhicules de prestige disponibles à la location avec chauffeur. Des limousines élégantes aux voitures de sport, nous avons le véhicule parfait pour chaque occasion.'),
(9, 'allservices', 'Accédez à l\'ensemble de nos services exclusifs pour une expérience complète et personnalisée. Hôtels, restaurants, spas, transport, événements et voyages — tout ce dont vous avez besoin pour un séjour d\'exception.');

INSERT INTO `partner` (`id`, `name`, `address`, `phone`, `description`, `link`, `service_id`) VALUES
(1,  'Le Grand Hôtel Paris',        '2 Rue Scribe, 75009 Paris',                '01 40 07 32 32', 'Hôtel 5 étoiles au cœur de Paris, face à l\'Opéra Garnier. Chambres somptueuses et service irréprochable.',          'https://www.legrandhotel.fr',         1),
(2,  'Hôtel de Crillon',            '10 Place de la Concorde, 75008 Paris',     '01 44 71 15 00', 'Palace parisien emblématique sur la Place de la Concorde. Luxe absolu et histoire au rendez-vous.',                 'https://www.rosewoodhotels.com',      1),
(3,  'Hôtel Hermitage Monaco',      'Square Beaumarchais, 98000 Monaco',        '+377 98 06 40 00','Hôtel de luxe dominant la Méditerranée à Monaco. Vue imprenable et prestations d\'exception.',                    'https://www.hotelhermitagemontecarlo.com', 1),
(4,  'Le Jules Verne',              'Tour Eiffel, Av. Gustave Eiffel, 75007 Paris','01 45 55 61 44','Restaurant gastronomique perché au 2e étage de la Tour Eiffel. Une expérience culinaire unique sur les toits de Paris.','https://www.lejulesverne-paris.com', 2),
(5,  'Guy Savoy',                   '11 Quai de Conti, 75006 Paris',            '01 43 80 40 61', 'Table triplement étoilée au guide Michelin. Cuisine française inventive dans un cadre architectural remarquable.',   'https://www.guysavoy.com',            2),
(6,  'Le Louis XV - Alain Ducasse', 'Place du Casino, 98000 Monaco',            '+377 98 06 88 64','Trois étoiles Michelin au cœur de Monaco. La quintessence de la cuisine méditerranéenne par Alain Ducasse.',        'https://www.ducasse-paris.com',       2),
(7,  'Cinq Mondes Spa Paris',       '6 Square de l\'Opéra, 75009 Paris',        '01 42 66 00 60', 'Spa urbain de luxe proposant des rituels bien-être inspirés des cinq continents au cœur de Paris.',                'https://www.cinqmondes.com',          3),
(8,  'Spa Nuxe',                    '32 Rue Montorgueil, 75001 Paris',          '01 55 80 71 40', 'Spa parisien iconique installé dans de magnifiques caves voûtées du XVIIe siècle. Soins signature Nuxe.',           'https://www.nuxe.com',               3),
(9,  'Thermes Marins Monte-Carlo',  '2 Avenue de Monte-Carlo, 98000 Monaco',    '+377 98 06 69 00','Centre de thalassothérapie et spa face à la mer. Soins exclusifs avec eau de mer et produits marins.',             'https://www.thermesmarinsmontecarlo.com', 3),
(10, 'Chauffeur Privé Elite',       '15 Avenue Montaigne, 75008 Paris',         '01 80 20 20 20', 'Service de chauffeurs privés haut de gamme disponible 24h/24. Flotte de véhicules de prestige.',                   'https://www.chauffeurelit.fr',        4),
(11, 'VIP Limousines',              '8 Rue du Faubourg Saint-Honoré, 75008 Paris','01 47 42 00 00','Location de limousines avec chauffeur pour tous vos déplacements. Discrétion et élégance garanties.',              'https://www.viplimousines.fr',        4),
(12, 'Monaco VTC',                  '1 Avenue des Spélugues, 98000 Monaco',     '+377 93 50 56 28','Service de voitures avec chauffeur à Monaco et sur la Côte d\'Azur. Transferts aéroport et excursions privées.',   'https://www.monaco-vtc.com',          4),
(13, 'Agence Événements Prestige',  '22 Rue du Colisée, 75008 Paris',           '01 53 75 22 00', 'Organisation d\'événements privés et corporate sur mesure. Soirées de gala, cocktails et séminaires d\'exception.', 'https://www.evenements-prestige.fr',  5),
(14, 'Les Grandes Tablées',         '5 Rue de Valois, 75001 Paris',             '01 42 96 65 00', 'Spécialiste des dîners privés et réceptions dans des lieux d\'exception parisiens. Chef étoilé à domicile.',        'https://www.lesgrandestablees.fr',    5),
(15, 'Monaco Events',               '10 Boulevard des Moulins, 98000 Monaco',   '+377 97 98 10 00','Organisation d\'événements exclusifs à Monaco. Accès aux lieux les plus prestigieux de la principauté.',           'https://www.monaco-events.com',       5),
(16, 'Voyages Lumière',             '36 Avenue de l\'Opéra, 75002 Paris',       '01 42 61 50 00', 'Agence de voyages de luxe proposant des circuits sur mesure dans les destinations les plus exclusives du monde.',    'https://www.voyageslumiere.fr',       6),
(17, 'Jet Set Travel',              '18 Avenue George V, 75008 Paris',          '01 47 20 74 00', 'Spécialiste du voyage privé en jet, yacht et hélicoptère. Des itinéraires uniques pour une clientèle exigeante.',   'https://www.jetsettravel.fr',         6),
(18, 'Évasion Côte d\'Azur',        '3 Promenade des Anglais, 06000 Nice',      '04 93 16 00 00', 'Agence spécialisée dans les séjours haut de gamme sur la Côte d\'Azur. Villas privées et expériences exclusives.',  'https://www.evasioncotedazur.fr',     6),
(19, 'Hôtel Negresco',              '37 Promenade des Anglais, 06000 Nice',     '04 93 16 64 00', 'Institution de la Côte d\'Azur, ce palace niçois allie art, histoire et raffinement depuis 1913.',                 'https://www.hotel-negresco-nice.com', 1),
(20, 'La Chèvre d\'Or',             'Rue du Barri, 06360 Èze',                  '04 92 10 66 66', 'Restaurant étoilé perché dans le village médiéval d\'Èze avec une vue spectaculaire sur la Méditerranée.',         'https://www.chevredor.com',           2);

